"""Initial schema

Revision ID: d378c9a67518
Revises:
Create Date: 2025-11-28 05:00:47.474609+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d378c9a67518"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database to this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Human-readable company name",
        ),
        sa.Column(
            "slug",
            sa.String(length=100),
            nullable=False,
            comment="URL-safe identifier (e.g., 'acme-corp')",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the tenant account is active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "environments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable name (e.g., 'Production')",
        ),
        sa.Column(
            "key",
            sa.String(length=50),
            nullable=False,
            comment="Machine-readable key (e.g., 'production')",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional description of the environment",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            comment="Whether this is the default environment for the tenant",
        ),
        sa.Column(
            "color",
            sa.String(length=7),
            nullable=False,
            comment="Hex color for UI display",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_environments_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environments")),
    )
    op.create_index(
        op.f("ix_environments_tenant_id"), "environments", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_environments_tenant_key", "environments", ["tenant_id", "key"], unique=True
    )
    op.create_table(
        "flags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
            comment="Tenant that owns this flag (multi-tenancy key)",
        ),
        sa.Column(
            "key",
            sa.String(length=100),
            nullable=False,
            comment="Machine-readable key (e.g., 'dark-mode')",
        ),
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Human-readable name"
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Detailed description of what this flag controls",
        ),
        sa.Column(
            "rollout_percentage",
            sa.Integer(),
            nullable=False,
            comment="Percentage of users who see the feature (0-100)",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Master switch - if False, flag always evaluates to False",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Current state: active, inactive, archived",
        ),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Optional tags for organization (e.g., {'team': 'payments'})",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rollout_percentage >= 0 AND rollout_percentage <= 100",
            name=op.f("ck_flags_ck_flags_rollout_percentage_range"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_flags_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flags")),
    )
    op.create_index(op.f("ix_flags_tenant_id"), "flags", ["tenant_id"], unique=False)
    op.create_index("ix_flags_tenant_key", "flags", ["tenant_id", "key"], unique=True)
    op.create_index(
        "ix_flags_tenant_status", "flags", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Human-readable name for identification",
        ),
        sa.Column(
            "key_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 hash of the full API key",
        ),
        sa.Column(
            "key_prefix",
            sa.String(length=12),
            nullable=False,
            comment="Prefix for key identification (e.g., 'xc_live_a1b2')",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether the API key is currently valid",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp of last successful authentication",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
            name=op.f("fk_api_keys_environment_id_environments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_api_keys_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
    )
    op.create_index(
        op.f("ix_api_keys_environment_id"), "api_keys", ["environment_id"], unique=False
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(
        op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False
    )
    op.create_index(
        op.f("ix_api_keys_tenant_id"), "api_keys", ["tenant_id"], unique=False
    )
    op.create_table(
        "flag_audit_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("flag_id", sa.UUID(), nullable=False),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
            comment="Denormalized for efficient multi-tenant queries",
        ),
        sa.Column(
            "action",
            sa.String(length=30),
            nullable=False,
            comment="Type of action: created, updated, deleted, etc.",
        ),
        sa.Column(
            "changes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Before/after values for the change",
        ),
        sa.Column(
            "actor_id",
            sa.UUID(),
            nullable=True,
            comment="UUID of the user who made the change",
        ),
        sa.Column(
            "actor_email",
            sa.String(length=255),
            nullable=True,
            comment="Email of the actor (denormalized for display)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["flag_id"],
            ["flags.id"],
            name=op.f("fk_flag_audit_logs_flag_id_flags"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_flag_audit_logs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag_audit_logs")),
    )
    op.create_index(
        "ix_flag_audit_logs_flag_created",
        "flag_audit_logs",
        ["flag_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flag_audit_logs_flag_id"), "flag_audit_logs", ["flag_id"], unique=False
    )
    op.create_index(
        "ix_flag_audit_logs_tenant_created",
        "flag_audit_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_flag_audit_logs_tenant_id"),
        "flag_audit_logs",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database from this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_flag_audit_logs_tenant_id"), table_name="flag_audit_logs")
    op.drop_index("ix_flag_audit_logs_tenant_created", table_name="flag_audit_logs")
    op.drop_index(op.f("ix_flag_audit_logs_flag_id"), table_name="flag_audit_logs")
    op.drop_index("ix_flag_audit_logs_flag_created", table_name="flag_audit_logs")
    op.drop_table("flag_audit_logs")
    op.drop_index(op.f("ix_api_keys_tenant_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_environment_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("ix_flags_tenant_status", table_name="flags")
    op.drop_index("ix_flags_tenant_key", table_name="flags")
    op.drop_index(op.f("ix_flags_tenant_id"), table_name="flags")
    op.drop_table("flags")
    op.drop_index("ix_environments_tenant_key", table_name="environments")
    op.drop_index(op.f("ix_environments_tenant_id"), table_name="environments")
    op.drop_table("environments")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
